name: publish

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 15 * * *"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: r7kamura/weneedfeed-action@v3
        with:
          base_url: https://shishi.github.io/weneedfeed-comic-ride
      - uses: actions/upload-pages-artifact@v3
        with:
          path: output
  deploy:
    needs: build
    permissions:
      actions: read
      id-token: write
      pages: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/deploy-pages@v4
        id: deployment
